language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
before_install:
  - bundle install
script:
  - 'if [[ ! "$TRAVIS_RUBY_VERSION" =~ "jruby" ]] ; then rake make ; fi'
  - rake spec